# Generated by Django 4.2 on 2025-07-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_aboutus_title_ru_aboutus_title_uz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='image',
            field=models.ImageField(upload_to='kasimov/about_us/'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to='kasimov/gallery/'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='icon',
            field=models.ImageField(upload_to='kasimov/partner/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(upload_to='kasimov/service/image/'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='image',
            field=models.ImageField(upload_to='kasimov/service_category/image/'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='video',
            field=models.FileField(upload_to='kasimov/service_category/video/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(upload_to='kasimov/team/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='kasimov/videos/'),
        ),
    ]
