# Generated by Django 4.2 on 2025-07-20 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_remove_service_image_service_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='description',
        ),
        migrations.RemoveField(
            model_name='service',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='service',
            name='description_uz',
        ),
        migrations.RemoveField(
            model_name='service',
            name='title',
        ),
        migrations.RemoveField(
            model_name='service',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='service',
            name='title_uz',
        ),
    ]
